on: 
    push:
        branches:
            - main
jobs:
    build-and-release:
        runs-on: ubuntu-latest
        if: contains(${{ github.ref }}, {-prerelease}) || contains(${{ github.ref }}, {-release}) 
        steps:
            - name: Install TexLive
              run: sudo apt-get update && sudo apt-get install texlive-full
            - name: Clone
              run: git clone https://github.com/TUST-Open-Source-Club/chapter
            - name: Compile
              run: cd chapter && xelatex Chapter.tex
            - name: Create Release
              uses: actions/create-release@v1
              if: contains(${{ github.ref }}, -prerelease)
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: Release ${{ github.ref }}
                draft: false
                prerelease: true
            - name: Create Release
              uses: actions/create-release@v1
              if: contains(${{ github.ref }}, -release)
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: Release ${{ github.ref }}
                draft: false
                prerelease: true
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./Chapter.pdf
                asset_name: 天津科技大学开放原子开源软件协会章程.pdf