on: 
    push:
        tags:
            - 'release/**'
jobs:
    build-and-release:
        permissions:
          contents: write
          discussions: write
        runs-on: ubuntu-latest
        if: contains(${{ github.ref }}, tag)
        steps:
            - uses: actions/checkout@v2
            - uses: docker://ghcr.io/qjoly/xelatex:latest
              with:
                args: |
                  Chapter.tex
            - name: Release
              uses: softprops/action-gh-release@v2
              if: github.ref_type == 'tag'
              with:
                repository: TUST-Open-Source-Club/chapter 
                # note you'll typically need to create a personal access token
                # with permissions to create releases in the other repo
                token: ${{ secrets.GITHUB_TOKEN }}
                files: Chapter.pdf
                prerelease: true
                name: 20250918-draft2